set timeout 60

#set scripts [glob vm_*.sh]
eval spawn scp -P 12066 [glob vm_*.sh] root@localhost:~/
while 1 {
	expect {
		eof	{break}
		"fingerprint"	{send "yes\r"}
		"password:"	{send "openEuler12#$\r" ; break}
	}
}

spawn ssh -p 12066 root@localhost
expect {
	"fingerprint"	{send "yes\r"}
	"password:"	{send "openEuler12#$\r" }
}
expect {
	eof	{break}
	"root@openEuler"	{send "bash vm_import_pubkey.sh; bash vm_config.sh\r"}
}
interact
